// <auto-generated />
namespace WebApi2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class KullaniciRequiredAlanlar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KullaniciRequiredAlanlar));
        
        string IMigrationMetadata.Id
        {
            get { return "202109250705153_KullaniciRequiredAlanlar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
